language: rust
rust: nightly
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

jobs:
  include:
    - stage: unit test
      os: linux
      dist: xenial
      script:
        - make build/swap-install && make test
    - stage: unit test
      os: osx
      osx_image: xcode11.3
      script:
        - make build/swap-install && make test
    - stage: lint
      os: linux
      dist: bionic
      before_script:
        - rustup component add rustfmt clippy --toolchain $(cat rust-toolchain)
      script:
        - make build/swap-install && make check-format && make lint
env:
  global:
    - RUST_BACKTRACE=1
install:
  - make setup
