[package]
name = "swap_proxy"
version = "0.1.0"
authors = ["Bryan <psy2848048@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
